

addcircle;
set("x",0);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",0);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",0);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",0);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",0);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",500);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",500);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",500);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",500);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",500);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",1000);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",1000);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",1000);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",1000);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",1000);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",1500);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",1500);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",1500);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",1500);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",1500);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",2000);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",2000);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",2000);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",2000);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",2000);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",2500);
set("y",2500);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",2500);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",3000);
set("radius",100e-9);



addcircle;
set("x",3000);
set("y",3500);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",2500);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",3000);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",3500);
set("radius",100e-9);



addcircle;
set("x",3500);
set("y",4000);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",2500);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",3000);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",3500);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",4000);
set("radius",100e-9);



addcircle;
set("x",4000);
set("y",4500);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",0);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",500);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",1000);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",1500);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",2000);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",2500);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",3000);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",3500);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",4000);
set("radius",100e-9);



addcircle;
set("x",4500);
set("y",4500);
set("radius",100e-9);

